server:
  port: 8080
      
spring:
  application:
    name: 'client'
    
  datasource:
    url: jdbc:postgres://zllsaacohshilx:8c95524b0f2118147cd75208c5dc4f0785d5e016449aaacfb82d0ca6a260cf36@ec2-3-231-241-17.compute-1.amazonaws.com:5432/d71r6sfm2otloh
    username: zllsaacohshilx
    password: 8c95524b0f2118147cd75208c5dc4f0785d5e016449aaacfb82d0ca6a260cf36
    hikari:
      maximum-pool-size: 3

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: poc

  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: poc