server:
  port: 8080
      
spring:
  application:
    name: 'client'
    
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 3

  jpa:
    hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: poc

  flyway:
    baseline-on-migrate: true
    enabled: true
    schemas: poc